### ISSUE TITLE
Unhandled System.Runtime.Serialization.SerializationException: "DateTime values that are greater than DateTime.MaxValue or smaller than DateTime.MinValue when converted to UTC cannot be serialized to JSON."

### ISSUE THREAD

**Issue by dtr** [Microsoft/Windows-appsample-remote-system-sessions#1]
On the Quiz Host the following exception occurred after quiz has been started with one remote client.
System.Runtime.Serialization.SerializationException ist aufgetreten.
  HResult=0x80131500
  Nachricht = DateTime values that are greater than DateTime.MaxValue or smaller than DateTime.MinValue when converted to UTC cannot be serialized to JSON.
  Quelle = <Die Ausnahmequelle kann nicht ausgewertet werden.>
  Stapelüberwachung:
   at System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTimeInDefaultFormat(DateTime value)
   at System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTime(DateTime value)
   at System.Runtime.Serialization.Json.JsonClassDataContract.WriteJsonValueCore(XmlWriterDelegator jsonWriter, Object obj, XmlObjectSerializerWriteContextComplexJson context, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
   at QuizGame.SessionManager.<SendMessageToParticipantsAsync>d__39.MoveNext() in f:\dtr\Documents\Visual Studio 2017\Projects\Windows-appsample-remote-system-sessions-master\QuizGame\SessionManager.cs:line 286
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at QuizGame.ViewModels.LobbyHostViewModel.<StartGame>d__5.MoveNext() in f:\dtr\Documents\Visual Studio 2017\Projects\Windows-appsample-remote-system-sessions-master\QuizGame\ViewModels\LobbyHostViewModel.cs:line 66

Innere Ausnahme 1:
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

**Comment by KarlErickson** [comment]
@dtr Thanks for letting us know about this! I've just checked in a fix.
